---
title: "DSCI 478: Final Paper"
author: "Trevor Isaacson and Evan Kessler"
date: "4/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Instructions from the syllabus:

From the syllabus:

The final paper should be 5–10 pages long; a PDF file (this can be generated from a DOCX or Google Doc file); font size 12; and double-spaced. The paper should have an introduction where the topic covered is properly motivated. All material coming from a third party – including images – should be properly cited where the material appears in the paper. The overwhelming majority of the paper should be your own wording; even if there is a citation, it is not acceptable to copy blocks of multiple sentences. There should be at least 3 sources which you have actually used listed. The sources should be peer-reviewed journals, (non- textbook) book chapters, or popular science magazine articles. Some blog entries are high quality enough to be used; please ask me if you are unsure. Sources like Wikipedia will not be considered acceptable but may be used as a starting point to find good sources. You may use any citation style of your choosing, but you must be consistent. The paper should be free or almost free of grammatical and spelling errors.

The code may be in any programming language. The code itself should be well-documented. The code file(s) may be text files or the original file format (e.g, .py, .r). Your code submis- sion should also include any pertinent data as well as a copy of the original article. You must upload your code to Canvas by May 4 at 3:00 p.m. MDT Alternatively, you may enter a link in the textbox on Canvas so that I may access your code on GitHub or similar repository.

The paper, code, and data must be uploaded to Canvas by May 4 at 3:00 p.m. Note that since other students will need to read the paper to give feedback, you need to have a nearly finished draft of the paper completed well before the submission deadline.

