---
title: "FoCo Research"
author: "Trevor Isaacson and Evan Kessler"
date: "4/24/2022"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
set.seed(445)
knitr::opts_chunk$set(echo = FALSE)
# knitr::opts_chunk$set(fig.width=5, fig.height=3) 
knitr::opts_chunk$set(message = FALSE)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(e1071)
library(rmarkdown)
library(glmnet)
library(knitr)
library(dplyr)
library(zoo)
library(tree)
library(randomForest)
```

```{r}
# station 46080 near Kodiak, Alaska
kodiak2019 = read.delim("./buoyData/kodiak2019.txt", header = FALSE, sep = "") 
colnames(kodiak2019) = c("Year", "Month", "Day", "Hour", "Minute", "WindDir", "WindSpeed", "GustSpeed", "WaveHeight", "DominantWavePeriod", "AverageWavePeriod", "DirWavePeriod", "SeaLevelPressure", "AirTemp", "SeaSurfaceTemp", "DewpointTemp", "Visibility", "Tide")
kodiak2019 = kodiak2019[-c(1:4),]
kodiak2019

# station 46089 near Tillamook, Oregon
tillamook2019 = read.delim("./buoyData/tillamook2019.txt", header = FALSE, sep = "") 
colnames(tillamook2019) = c("Year", "Month", "Day", "Hour", "Minute", "WindDir", "WindSpeed", "GustSpeed", "WaveHeight", "DominantWavePeriod", "AverageWavePeriod", "DirWavePeriod", "SeaLevelPressure", "AirTemp", "SeaSurfaceTemp", "DewpointTemp", "Visibility", "Tide")
tillamook2019 = tillamook2019[-c(1:3),]
tillamook2019

# station 46059 near Western California Coast
westCali2019 = read.delim("./buoyData/westcali2019.txt", header = FALSE, sep = "") 
colnames(westCali2019) = c("Year", "Month", "Day", "Hour", "Minute", "WindDir", "WindSpeed", "GustSpeed", "WaveHeight", "DominantWavePeriod", "AverageWavePeriod", "DirWavePeriod", "SeaLevelPressure", "AirTemp", "SeaSurfaceTemp", "DewpointTemp", "Visibility", "Tide")
westCali2019 = westCali2019[-c(1:3),]
# the measurements we want are measured at minute 40
westCali2019 = westCali2019 %>%
  filter(Minute == 40)
westCali2019

# station 46084 near Cape Edgecumbe, Alaska
cape2019 = read.delim("./buoyData/capeEdgecumbe2019.txt", header = FALSE, sep = "") 
colnames(cape2019) = c("Year", "Month", "Day", "Hour", "Minute", "WindDir", "WindSpeed", "GustSpeed", "WaveHeight", "DominantWavePeriod", "AverageWavePeriod", "DirWavePeriod", "SeaLevelPressure", "AirTemp", "SeaSurfaceTemp", "DewpointTemp", "Visibility", "Tide")
cape2019 = cape2019[-c(1:3),]
cape2019
```


New Buoy Hourly Data for 2019
```{r}
tillamook2019 = tillamook2019 %>%
  mutate(WindSpeed = as.numeric(as.character(WindSpeed))) %>%
  mutate(GustSpeed = as.numeric(as.character(GustSpeed))) %>%
  mutate(AirTemp = as.numeric(as.character(AirTemp))) %>%
  mutate(SeaSurfaceTemp = as.numeric(as.character(SeaSurfaceTemp))) %>%
  mutate(DewpointTemp = as.numeric(as.character(DewpointTemp))) %>%
  mutate(WaveHeight = as.numeric(as.character(WaveHeight))) %>%
  mutate(DominantWavePeriod = as.numeric(as.character(DominantWavePeriod))) %>%
  mutate(AverageWavePeriod = as.numeric(as.character(AverageWavePeriod))) %>%
  mutate(DirWavePeriod = as.numeric(as.character(DirWavePeriod))) %>%
  mutate(SeaLevelPressure = as.numeric(as.character(SeaLevelPressure))) %>%
  mutate(WindDir = as.numeric(as.character(WindDir))) %>%
  mutate(Day = as.numeric(as.character(Day))) %>%
  mutate(Month = as.numeric(as.character(Month))) %>%
  mutate(Year = as.numeric(as.character(Year))) %>%
  filter(WaveHeight != 99.00) %>%
  select(-c(Visibility, Tide))

westCali2019 = westCali2019 %>%
  mutate(WindSpeed = as.numeric(as.character(WindSpeed))) %>%
  mutate(GustSpeed = as.numeric(as.character(GustSpeed))) %>%
  mutate(AirTemp = as.numeric(as.character(AirTemp))) %>%
  mutate(SeaSurfaceTemp = as.numeric(as.character(SeaSurfaceTemp))) %>%
  mutate(DewpointTemp = as.numeric(as.character(DewpointTemp))) %>%
  mutate(WaveHeight = as.numeric(as.character(WaveHeight))) %>%
  mutate(DominantWavePeriod = as.numeric(as.character(DominantWavePeriod))) %>%
  mutate(AverageWavePeriod = as.numeric(as.character(AverageWavePeriod))) %>%
  mutate(DirWavePeriod = as.numeric(as.character(DirWavePeriod))) %>%
  mutate(SeaLevelPressure = as.numeric(as.character(SeaLevelPressure))) %>%
  mutate(WindDir = as.numeric(as.character(WindDir))) %>%
  mutate(Day = as.numeric(as.character(Day))) %>%
  mutate(Month = as.numeric(as.character(Month))) %>%
  mutate(Year = as.numeric(as.character(Year))) %>%
  filter(WaveHeight != 99.00) %>%
  select(-c(Visibility, Tide))

cape2019 = cape2019 %>%
  mutate(WindSpeed = as.numeric(as.character(WindSpeed))) %>%
  mutate(GustSpeed = as.numeric(as.character(GustSpeed))) %>%
  mutate(AirTemp = as.numeric(as.character(AirTemp))) %>%
  mutate(SeaSurfaceTemp = as.numeric(as.character(SeaSurfaceTemp))) %>%
  mutate(DewpointTemp = as.numeric(as.character(DewpointTemp))) %>%
  mutate(WaveHeight = as.numeric(as.character(WaveHeight))) %>%
  mutate(DominantWavePeriod = as.numeric(as.character(DominantWavePeriod))) %>%
  mutate(AverageWavePeriod = as.numeric(as.character(AverageWavePeriod))) %>%
  mutate(DirWavePeriod = as.numeric(as.character(DirWavePeriod))) %>%
  mutate(SeaLevelPressure = as.numeric(as.character(SeaLevelPressure))) %>%
  mutate(WindDir = as.numeric(as.character(WindDir))) %>%
  mutate(Day = as.numeric(as.character(Day))) %>%
  mutate(Month = as.numeric(as.character(Month))) %>%
  mutate(Year = as.numeric(as.character(Year))) %>%
  filter(WaveHeight != 99.00) %>%
  select(-c(Visibility, Tide))
```

```{r}
# average data on daily basis
tillamook2019 = tillamook2019 %>%
  group_by(Year, Month, Day) %>%
  summarise(across(c(WindDir:DewpointTemp), ~ mean(.x, na.rm = TRUE)))
  
westCali2019 = westCali2019 %>%
  group_by(Year, Month, Day) %>%
  summarise(across(c(WindDir:DewpointTemp), ~ mean(.x, na.rm = TRUE)))

cape2019 = cape2019 %>%
  group_by(Year, Month, Day) %>%
  summarise(across(c(WindDir:DewpointTemp), ~ mean(.x, na.rm = TRUE)))

tillamook2019
westCali2019
cape2019
```



Fort Collins Snow Totals 
```{r warning = FALSE}
FC2019 = read.csv("./snowfallData/FoCoSnowfall2019.csv")
FC2020 = read.csv("./snowfallData/FoCoSnowfall2020.csv")

# change M, T and - to 0
FC2019 = FC2019 %>%
  mutate_if(is.factor, as.character) %>%
  mutate_if(is.character, as.numeric)
FC2019[is.na(FC2019)] <- 0

FC2020 = FC2020 %>%
  mutate_if(is.factor, as.character) %>%
  mutate_if(is.character, as.numeric)
FC2020[is.na(FC2020)] <- 0

FoCoSnowTotals2019 = stack(FC2019[2:ncol(FC2019)])
FoCoSnowTotals2019 = FoCoSnowTotals2019[-c(60,61,62,124,168,186,249,341), ]

# advanced snowfall = oregon/california snow 5-7 days in advance
# remove first 7 days of year
advanceSnowTotals5Days = FoCoSnowTotals2019[-c(1:5), ]
advanceSnowTotals6Days = FoCoSnowTotals2019[-c(1:6), ]
advanceSnowTotals7Days = FoCoSnowTotals2019[-c(1:7), ]
advanceSnowTotals7Days = FoCoSnowTotals2019[-c(1:8), ]
advanceSnowTotals7Days = FoCoSnowTotals2019[-c(1:9), ]

# add first 14 days of next year to end
SnowTotals5Daysinto2020 = FC2020[1:5, "Jan"]
SnowTotals6Daysinto2020 = FC2020[1:6, "Jan"]
SnowTotals7Daysinto2020 = FC2020[1:7, "Jan"]
SnowTotals7Daysinto2020 = FC2020[1:8, "Jan"]
SnowTotals7Daysinto2020 = FC2020[1:9, "Jan"]

SnowTotals5Daysinto2020 = data.frame(values = SnowTotals5Daysinto2020, ind = "Jan")
SnowTotals6Daysinto2020 = data.frame(values = SnowTotals6Daysinto2020, ind = "Jan")
SnowTotals7Daysinto2020 = data.frame(values = SnowTotals7Daysinto2020, ind = "Jan")
SnowTotals8Daysinto2020 = data.frame(values = SnowTotals8Daysinto2020, ind = "Jan")
SnowTotals9Daysinto2020 = data.frame(values = SnowTotals9Daysinto2020, ind = "Jan")

advancedSnowfall5 = rbind(advanceSnowTotals5Days, SnowTotals5Daysinto2020)
advancedSnowfall6 = rbind(advanceSnowTotals6Days, SnowTotals6Daysinto2020)
advancedSnowfall7 = rbind(advanceSnowTotals7Days, SnowTotals7Daysinto2020)
advancedSnowfall8 = rbind(advanceSnowTotals8Days, SnowTotals8Daysinto2020)
advancedSnowfall9 = rbind(advanceSnowTotals9Days, SnowTotals9Daysinto2020)

# create dataframe of snowfalls 
newFC2019 = data.frame(Year = westCali2019$Year,
                             Month = westCali2019$Month,
                             Day = westCali2019$Day,
                             Snowfall = FoCoSnowTotals2019$values,
                             Snowfall5DaysLater = advancedSnowfall5$values,
                             Snowfall6DaysLater = advancedSnowfall6$values,
                             Snowfall7DaysLater = advancedSnowfall7$values,
                             Snowfall8DaysLater = advancedSnowfall8$values,
                             Snowfall9DaysLater = advancedSnowfall9$values)
FC2019 = newFC2019
```

Breckenridge Snow Totals 
```{r warning = FALSE}
B2019 = read.csv("./snowfallData/BreckSnowfall2019.csv")
B2020 = read.csv("./snowfallData/BreckSnowfall2020.csv")

# change M, T and - to 0
B2019 = B2019 %>%
  mutate_if(is.factor, as.character) %>%
  mutate_if(is.character, as.numeric)
B2019[is.na(B2019)] <- 0

B2020 = B2020 %>%
  mutate_if(is.factor, as.character) %>%
  mutate_if(is.character, as.numeric)
B2020[is.na(B2020)] <- 0

BreckSnowTotals2019 = stack(B2019[2:ncol(B2019)])
BreckSnowTotals2019 = BreckSnowTotals2019[-c(60,61,62,124,168,186,249,341), ]

# advanced snowfall = oregon/california snow 5-7 days in advance
# remove first 7 days of year
advanceSnowTotals5Days = BreckSnowTotals2019[-c(1:5), ]
advanceSnowTotals6Days = BreckSnowTotals2019[-c(1:6), ]
advanceSnowTotals7Days = BreckSnowTotals2019[-c(1:7), ]
advanceSnowTotals8Days = BreckSnowTotals2019[-c(1:8), ]
advanceSnowTotals9Days = BreckSnowTotals2019[-c(1:9), ]

# add first 14 days of next year to end
SnowTotals5Daysinto2020 = B2020[1:5, "Jan"]
SnowTotals6Daysinto2020 = B2020[1:6, "Jan"]
SnowTotals7Daysinto2020 = B2020[1:7, "Jan"]
SnowTotals8Daysinto2020 = B2020[1:8, "Jan"]
SnowTotals9Daysinto2020 = B2020[1:9, "Jan"]

SnowTotals5Daysinto2020 = data.frame(values = SnowTotals5Daysinto2020, ind = "Jan")
SnowTotals6Daysinto2020 = data.frame(values = SnowTotals6Daysinto2020, ind = "Jan")
SnowTotals7Daysinto2020 = data.frame(values = SnowTotals7Daysinto2020, ind = "Jan")
SnowTotals8Daysinto2020 = data.frame(values = SnowTotals8Daysinto2020, ind = "Jan")
SnowTotals9Daysinto2020 = data.frame(values = SnowTotals9Daysinto2020, ind = "Jan")

advancedSnowfall5 = rbind(advanceSnowTotals5Days, SnowTotals5Daysinto2020)
advancedSnowfall6 = rbind(advanceSnowTotals6Days, SnowTotals6Daysinto2020)
advancedSnowfall7 = rbind(advanceSnowTotals7Days, SnowTotals7Daysinto2020)
advancedSnowfall8 = rbind(advanceSnowTotals8Days, SnowTotals8Daysinto2020)
advancedSnowfall9 = rbind(advanceSnowTotals9Days, SnowTotals9Daysinto2020)

# create dataframe of snowfalls 
newB2019 = data.frame(Year = westCali2019$Year,
                             Month = westCali2019$Month,
                             Day = westCali2019$Day,
                             Snowfall = BreckSnowTotals2019$values,
                             Snowfall5DaysLater = advancedSnowfall5$values,
                             Snowfall6DaysLater = advancedSnowfall6$values,
                             Snowfall7DaysLater = advancedSnowfall7$values, 
                             Snowfall8DaysLater = advancedSnowfall8$values,
                             Snowfall9DaysLater = advancedSnowfall9$values)
B2019 = newB2019
```


Add Snow Totals to Buoy Data for buoys with time distances of about 4 - 7 days
```{r}
# this dataframe has westCali buoy with FoCo snow totals
westCaliFoCo = westCali2019
westCaliFoCo["Snowfall"] = FC2019$Snowfall
westCaliFoCo["AvgSnowfall3DayWindow"] = (FC2019$Snowfall5DaysLater + FC2019$Snowfall6DaysLater + FC2019$Snowfall7DaysLater) /3 

# this dataframe has westCali buoy with Breck snow totals
westCaliBreck = westCali2019
westCaliBreck["Snowfall"] = B2019$Snowfall
westCaliBreck["AvgSnowfall3DayWindow"] = (B2019$Snowfall5DaysLater + B2019$Snowfall6DaysLater + B2019$Snowfall7DaysLater) /3 

# this dataframe has tillamook buoy with FoCo snow totals
tillamookFoCo = tillamook2019
tillamookFoCo["Snowfall"] = FC2019$Snowfall
tillamookFoCo["AvgSnowfall3DayWindow"] = (FC2019$Snowfall5DaysLater + FC2019$Snowfall6DaysLater + FC2019$Snowfall7DaysLater) /3 

# this dataframe has tillamook buoy with Breck snow totals
tillamookBreck = westCali2019
tillamookBreck["Snowfall"] = B2019$Snowfall
tillamookBreck["AvgSnowfall3DayWindow"] = (B2019$Snowfall5DaysLater + B2019$Snowfall6DaysLater + B2019$Snowfall7DaysLater) /3 
```

Add Snow Totals to Buoy Data for buoys with time distances of about 6 - 8 days
```{r}
capeFoCo = cape2019
capeFoCo["Snowfall"] = FC2019$Snowfall
capeFoCo["AvgSnowfall3DayWindow"] = (FC2019$Snowfall6DaysLater + FC2019$Snowfall7DaysLater + FC2019$Snowfall8DaysLater) /3 

# this dataframe has westCali buoy with Breck snow totals
capeBreck = cape2019
capeBreck["Snowfall"] = B2019$Snowfall
capeBreck["AvgSnowfall3DayWindow"] = (B2019$Snowfall6DaysLater + B2019$Snowfall7DaysLater + B2019$Snowfall8DaysLater) /3 
```







