---
title: "InitialResearch"
author: "Trevor Isaacson"
date: "3/27/2022"
output: html_document
---


Machine Learning and Cosine Similarity? Ask about slides
Difference in measurement start of day and end of day, compare that number with snowfall two weeks out
Average measurement compared with snowfall two weeks out 
```{r setup, include=FALSE, echo = FALSE}
set.seed(445)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width=5, fig.height=3) 
knitr::opts_chunk$set(message = FALSE)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(e1071)
library(rmarkdown)
library(glmnet)
library(knitr)
library(dplyr)
library(zoo)
```

## Original Buoy Data
```{r}
originalBuoy2019 = read.delim("./buoyData/originalBuoy2019.txt", header = FALSE, sep = "")
colnames(originalBuoy2019) = c("Year", "Month", "Day", "Hour", "Minute", "WindDir", "WindSpeed", "GustSpeed", "WaveHeight", "DominantWavePeriod", "AverageWavePeriod", "DirWavePeriod", "SeaLevelPressure", "AirTemp", "SeaSurfaceTemp", "DewpointTemp", "Visibility", "Tide")
originalBuoy2019 = originalBuoy2019[-c(1),]
originalBuoy2019
```

```{r}
# the measurements we want are measured at minute 40
originalBuoy2019 = originalBuoy2019 %>%
  # these aren't measured and remain static
  select(-c("Tide", "Visibility")) %>%
  filter(Minute == 40)

originalBuoy2019 = originalBuoy2019 %>%
  mutate(WindSpeed = as.numeric(as.character(WindSpeed))) %>%
  mutate(GustSpeed = as.numeric(as.character(GustSpeed))) %>%
  mutate(AirTemp = as.numeric(as.character(AirTemp))) %>%
  mutate(SeaSurfaceTemp = as.numeric(as.character(SeaSurfaceTemp))) %>%
  mutate(DewpointTemp = as.numeric(as.character(DewpointTemp))) %>%
  mutate(WaveHeight = as.numeric(as.character(WaveHeight))) %>%
  mutate(DominantWavePeriod = as.numeric(as.character(DominantWavePeriod))) %>%
  mutate(AverageWavePeriod = as.numeric(as.character(AverageWavePeriod))) %>%
  mutate(DirWavePeriod = as.numeric(as.character(DirWavePeriod))) %>%
  mutate(SeaLevelPressure = as.numeric(as.character(SeaLevelPressure))) %>%
  mutate(WindDir = as.numeric(as.character(WindDir))) %>%
  mutate(Day = as.numeric(as.character(Day))) %>%
  filter(WaveHeight != 99.00)

originalBuoy2019
```

```{r}
# create mean for every 4 hours, 12 hours and day
DailyData = originalBuoy2019 %>%
  group_by(Year, Month, Day) %>%
  summarise(across(c(WindDir:DewpointTemp), ~ mean(.x, na.rm = TRUE)))
  
DailyData
```


## Park City Snowfall Data
```{r}
ParkCity2019 = read.csv("./snowfallData/ParkCitySnowfall2019.csv")
ParkCity2020 = read.csv("./snowfallData/ParkCitySnowfall2020.csv")
```

```{r warning = FALSE}
# change M, T and - to 0
ParkCity2019 = ParkCity2019 %>%
  mutate_if(is.factor, as.character) %>%
  mutate_if(is.character, as.numeric)
ParkCity2019[is.na(ParkCity2019)] <- 0

ParkCity2020 = ParkCity2020 %>%
  mutate_if(is.factor, as.character) %>%
  mutate_if(is.character, as.numeric)
ParkCity2020[is.na(ParkCity2020)] <- 0

ParkCity2019
ParkCity2020
```

```{r}
ggplot(data = DailyData, aes(x = Day, y = WaveHeight)) +
  geom_line() +
  facet_wrap(~Month)

ggplot(data = ParkCity2019, aes(x = Day, y = Feb)) +
  geom_point() +
  geom_line()
```












